\c workbench;

INSERT INTO users (name, email, password) VALUES ('test', 'test@test.com', 'test123');

INSERT INTO languages (language_name, iso_code, requested) VALUES ('Afrikaans', 'af', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Akkadian', 'akk', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Akuntsu', 'aqz', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Albanian', 'sq', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Amharic', 'am', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Ancient Greek', 'grc', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Ancient Hebrew', 'hbo', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Apurina', 'apu', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Arabic', 'ar', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Armenian', 'hy', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Assyrian', 'aii', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Bambara', 'bm', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Basque', 'eu', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Beja', 'bej', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Belarusian', 'be', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Bengali', 'bn', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Bhojpuri', 'bho', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Breton', 'br', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Bulgarian', 'bg', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Buryat', 'bxr', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Cantonese', 'yue', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Catalan', 'ca', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Cebuano', 'ceb', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Chinese', 'zh', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Chukchi', 'ckt', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Classical Chinese', 'lzh', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Coptic', 'cop', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Croatian', 'hr', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Czech', 'cs', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Danish', 'da', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Dutch', 'nl', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('English', 'en', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Erzya', 'myv', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Estonian', 'et', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Faroese', 'fo', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Finnish', 'fi', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('French', 'fr', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Frisian Dutch', 'qfn', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Galician', 'gl', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('German', 'de', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Gothic', 'got', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Greek', 'el', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Guajajara', 'gub', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Guarani', 'gn', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Hebrew', 'he', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Hindi', 'hi', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Hindi English', 'qhe', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Hittite', 'hit', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Hungarian', 'hu', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Icelandic', 'is', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Indonesian', 'id', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Irish', 'ga', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Italian', 'it', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Japanese', 'ja', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Javanese', 'jv', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Kaapor', 'urb', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Kangri', 'xnr', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Karelian', 'krl', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Karo', 'arr', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Kazakh', 'kk', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Khunsari', 'kfm', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Kiche', 'quc', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Komi Permyak', 'koi', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Komi Zyrian', 'kpv', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Korean', 'ko', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Kurmanji', 'kmr', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Latin', 'la', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Latvian', 'lv', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Ligurian', 'lij', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Lithuanian', 'lt', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Livvi', 'olo', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Low Saxon', 'nds', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Madi', 'jaa', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Makurap', 'mpu', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Maltese', 'mt', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Manx', 'gv', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Marathi', 'mr', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Mbya Guarani', 'gun', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Moksha', 'mdf', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Munduruku', 'myu', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Naija', 'pcm', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Nayini', 'nyq', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Neapolitan', 'nap', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('North Sami', 'sme', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Norwegian', 'no', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Old Church Slavonic', 'cu', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Old East Slavic', 'orv', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Old French', 'fro', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Old Irish', 'sga', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Old Turkish', 'otk', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Persian', 'fa', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Polish', 'pl', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Pomak', 'qpm', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Portuguese', 'pt', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Romanian', 'ro', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Russian', 'ru', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Sanskrit', 'sa', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Scottish Gaelic', 'gd', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Serbian', 'sr', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Skolt Sami', 'sms', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Slovak', 'sk', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Slovenian', 'sl', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Soi', 'soj', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('South Levantine Arabic', 'ajp', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Spanish', 'es', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Swedish', 'sv', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Swedish Sign Language', 'swl', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Swiss German', 'gsw', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Tagalog', 'tl', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Tamil', 'ta', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Tatar', 'tt', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Teko', 'eme', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Telugu', 'te', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Thai', 'th', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Tupinamba', 'tpn', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Turkish', 'tr', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Turkish German', 'qtd', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Ukrainian', 'uk', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Umbrian', 'xum', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Upper Sorbian', 'hsb', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Urdu', 'ur', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Uyghur', 'ug', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Vietnamese', 'vi', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Warlpiri', 'wbp', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Welsh', 'cy', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Western Armenian', 'hyw', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Wolof', 'wo', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Xibe', 'sjo', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Yakut', 'sah', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Yoruba', 'yo', FALSE);
INSERT INTO languages (language_name, iso_code, requested) VALUES ('Yupik', 'ess', FALSE);


INSERT INTO uploaded_files (name, content, user_id, language_id) VALUES ('a.txt', 'Lorem ipsum dolor sit amet, consectetur adipiscing  elit. Donec eu urna iaculis, consequat ex et, suscipit arcu. Duis laoreet consectetur viverra. Mauris odio mauris, tempus nec libero nec, commodo hendrerit eros. Nullam porta et elit eget fermentum. Fusce vehicula ac eros bibendum consectetur. Sed maximus, risus id vestibulum imperdiet, ligula mi accumsan tellus, eget blandit eros magna tincidunt dolor. Praesent lobortis non quam ac sodales. Donec a ligula eu leo consequat porta sit amet id mauris. Integer bibendum purus id orci posuere volutpat. In efficitur elit vitae mauris volutpat, non pellentesque quam consequat. Cras dui risus, condimentum a tortor quis, volutpat pellentesque diam. Vivamus feugiat posuere erat ut sollicitudin. Quisque sed ex ac turpis tincidunt porttitor id at lectus. Pellentesque feugiat magna ut elit bibendum faucibus.', 1, 1);

INSERT INTO uploaded_files (name, content, user_id, language_id) VALUES ('b.txt', '.i. biuusa ocirbáig darfarcennsi frimaccidóndu\n\n.i. niarformut fribsi asbiursa inso arropad maith limsa labrad ilbelre dúibsi\n\n.i. isipersin crist dagníusa sin\n\n.i. ó domanicc foirbthetu ní denim gnímu macthi act rísam nem bimmi æcni et bimmi foirbthi uili\n\n.i. isocprecept soscéli attó\n\n.i. ished inso noguidimm .i. conducaid etargne ṅ dǽ et conaroib temel innatol domunde tarrosc fornanme\n\n.i. hore nondobmolorsa et nom móidim indib\n\n.i. amal nondafrecṅdirccsa\n\n.i. is inse ṅduit nitú nodnai(l) acht ishé not ail\n\n.i. madarlóg pridchasa .i. armetiuth et mothoschith nímbia fochricc dar hési moprecepte\n\n.i. coníarimse peccad libsi uili ɫ. aratartsa fortacht dúibsi arnap trom fuirib fornóinur\n\n.i. cote mothorbese dúib madamne labrar\n\n.i. nihed notbeir ínem ciabaloingthech\n\nAcht nammáa issamlid istorbe són co etercerta anasbera et conrucca inætarcne cáich\n\n.i. léic uáit innabiada mílsi ettomil innahí siu dommeil do chenél arnáphé som conéit détso\n\n	.i. isamlid dorígeni dia corp duini ó ilballaib\n\n	.i. act basamlid dúib cid immeícndarcus', 1, 2);

INSERT INTO tokens (token, reserved_token, start_index, end_index, token_language_id, type, uploaded_file_id) VALUES ('Lorem', TRUE, 0, 4, 1, 'manual', 1);

INSERT INTO tokens (token, reserved_token, start_index, end_index, token_language_id, type, uploaded_file_id) VALUES ('ipsum', TRUE, 6, 11, 1, 'manual', 1);

