export default {
    "ADJ": {
        "Abbr": ["Yes"],
        "Case": ["Abl", "Acc", "Dat", "Gen", "Nom", "Voc"],
        "Compound": ["Yes"],
        "Degree": ["Abs", "Cmp", "Cmp,Sup", "Pos", "Sup"],
        "ExtPos": ["ADP", "ADV", "SCONJ"],
        "Foreign": ["Yes"],
        "Form": ["Ecl", "HPref", "Len"],
        "Gender": ["Fem", "Fem,Masc", "Fem,Neut", "Masc", "Masc,Neut", "Neut"],
        "InflClass": ["Ind", "IndEurA", "IndEurI", "IndEurO", "IndEurX"],
        "NameType": ["Cal", "Com", "Geo", "Giv", "Lit", "Nat", "Rel", "Sur"],
        "NounType": ["NotSlender", "Slender", "Strong", "Weak"],
        "NumType": ["Dist", "Frac", "Mult", "Ord"],
        "Number": ["Dual", "Plur", "Sing"],
        "Polarity": ["Neg"],
        "Prefix": ["Yes"],
        "Proper": ["Yes"],
        "Style": ["Expr"],
        "Tense": ["Pres"],
        "Typo": ["Yes"],
        "Variant": ["Greek"],
        "VerbForm": ["Gdv", "Part"]
    },
    "ADP": {
        "Abbr": ["Yes"],
        "AdpType": ["Post", "Prep"],
        "Case": ["Nom"],
        "Clitic": ["Yes"],
        "Compound": ["Yes"],
        "Definite": ["Def", "Ind"],
        "Dialect": ["Connaught", "Munster", "Ulster"],
        "ExtPos": ["ADV"],
        "Foreign": ["Yes"],
        "Form": ["Ecl", "HPref", "Len"],
        "Gender": ["Fem", "Fem,Masc", "Masc", "Masc,Neut"],
        "Number": ["Plur", "Sing"],
        "Person": ["1", "2", "3"],
        "Poss": ["Yes"],
        "PrepForm": ["Cmpd"],
        "PronType": ["Art", "Emp", "Prs", "Prs,Rel", "Rel"],
        "Proper": ["Yes"],
        "Typo": ["Yes"],
        "VerbForm": ["Gdv", "Part"]
    },
    "ADV": {
        "Abbr": ["Yes"],
        "AdvType": ["Loc", "Tim"],
        "Case": ["Nom"],
        "Clitic": ["Yes"],
        "Compound": ["Yes"],
        "Degree": ["Abs", "Cmp", "Pos", "Sup"],
        "Dialect": ["Connaught"],
        "ExtPos": ["CCONJ"],
        "Form": ["Emp", "Len"],
        "NumForm": ["Word"],
        "NumType": ["Card", "Frac", "Mult", "Ord"],
        "Number": ["Plur", "Sing"],
        "Person": ["2"],
        "Polarity": ["Neg"],
        "PronType": ["Con", "Dem", "Ind", "Ind,Int", "Ind,Neg", "Int", "Int,Rel", "Neg", "Prs", "Rel", "Tot"],
        "Style": ["Expr"],
        "Tense": ["Past"],
        "Typo": ["Yes"],
        "VerbForm": ["Fin", "Gdv", "Part"]
    },
    "AUX": {
        "Abbr": ["Yes"],
        "Aspect": ["Hab", "Imp", "Perf"],
        "Case": ["Abl", "Acc", "Gen", "Nom"],
        "Degree": ["Pos"],
        "Dialect": ["Ulster"],
        "Form": ["Ecl", "Ecl,VF", "Len", "VF"],
        "Gender": ["Fem", "Masc", "Masc,Neut", "Neut"],
        "InflClass": ["LatAnom"],
        "InflClass[nominal]": ["Ind", "IndEurA", "IndEurI", "IndEurO"],
        "Mood": ["Cnd", "Imp", "Ind", "Int", "Sub"],
        "Number": ["Plur", "Sing"],
        "PartType": ["Aug"],
        "Person": ["1", "2", "3"],
        "Polarity": ["Neg", "Pos"],
        "PronType": ["Dem", "Rel"],
        "Style": ["Arch"],
        "Tense": ["Fut", "Past", "Pqp", "Pres"],
        "Typo": ["Yes"],
        "VerbForm": ["Cop", "Fin", "Ger", "Inf", "Part"],
        "VerbType": ["Cop"],
        "Voice": ["Act"]
    },
    "CCONJ": {
        "Abbr": ["Yes"],
        "AdvType": ["Loc"],
        "Case": ["Nom"],
        "Clitic": ["Yes"],
        "Compound": ["Yes"],
        "ConjType": ["Expl"],
        "Form": ["Emp"],
        "Polarity": ["Neg"],
        "PronType": ["Rel"],
        "Typo": ["Yes"],
        "VerbForm": ["Fin"]
    },
    "DET": {
        "Abbr": ["Yes"],
        "AdpType": ["Prep"],
        "Case": ["Abl", "Acc", "Dat", "Gen", "Loc", "Nom", "Voc"],
        "Clitic": ["Yes"],
        "Compound": ["Yes"],
        "Definite": ["Def", "Ind"],
        "Degree": ["Abs", "Cmp", "Pos"],
        "Dialect": ["Munster", "Ulster"],
        "Foreign": ["Yes"],
        "Form": ["Ecl", "Emp", "HPref", "Len"],
        "Gender": ["Fem", "Fem,Masc", "Fem,Neut", "Masc", "Masc,Neut", "Neut"],
        "InflClass": ["Ind", "IndEurA", "IndEurI", "IndEurO", "IndEurX", "LatPron"],
        "NumForm": ["Word"],
        "NumType": ["Card", "Frac"],
        "Number": ["Dual", "Plur", "Sing"],
        "Number[psor]": ["Plur", "Sing"],
        "Person": ["1", "2", "3"],
        "Person[psor]": ["1", "2", "3"],
        "Polarity": ["Neg"],
        "Poss": ["Yes"],
        "PronType": ["Art", "Con", "Dem", "Dem,Ind", "Dem,Prs", "Ind", "Ind,Neg", "Ind,Rel", "Int", "Int,Rel", "Neg", "Prs", "Rcp", "Rel", "Tot"],
        "Proper": ["Yes"],
        "Reflex": ["Yes"],
        "Typo": ["Yes"]
    },
    "INTJ": {
        "Abbr": ["Yes"],
        "Case": ["Nom"],
        "Degree": ["Pos"],
        "Number": ["Sing"],
        "Polarity": ["Neg"],
        "Style": ["Expr"],
        "Typo": ["Yes"]
    },
    "NOUN": {
        "Abbr": ["Yes"],
        "Case": ["Abl", "Acc", "Dat", "Gen", "Loc", "Nom", "Voc"],
        "Compound": ["Yes"],
        "Definite": ["Def", "Ind"],
        "Dialect": ["Connaught", "Munster", "Ulster"],
        "ExtPos": ["ADV"],
        "Foreign": ["Yes"],
        "Form": ["Ecl", "Emp", "Emp,Len", "HPref", "Len"],
        "Gender": ["Fem", "Fem,Masc", "Masc", "Masc,Neut", "Neut"],
        "InflClass": ["Ind", "IndEurA", "IndEurE", "IndEurI", "IndEurO", "IndEurU", "IndEurX"],
        "Mood": ["Ind"],
        "NameType": ["Ast", "Cal", "Com", "Geo", "Giv", "Let", "Lit", "Nat", "Rel", "Sur"],
        "NounType": ["Strong", "Weak"],
        "NumForm": ["Word"],
        "NumType": ["Frac", "Ord"],
        "Number": ["Dual", "Plur", "Sing"],
        "Polarity": ["Neg"],
        "Prefix": ["Yes"],
        "PrepForm": ["Cmpd"],
        "Proper": ["Yes"],
        "Style": ["Expr"],
        "Tense": ["Past"],
        "Typo": ["Yes"],
        "Variant": ["Greek"],
        "VerbForm": ["Fin", "Inf", "Part", "Sup", "Vnoun"]
    },
    "NUM": {
        "Abbr": ["Yes"],
        "Case": ["Abl", "Acc", "Dat", "Gen", "Nom"],
        "Compound": ["Yes"],
        "ExtPos": ["PRON"],
        "Form": ["Ecl", "HPref", "Len"],
        "Gender": ["Fem", "Fem,Masc", "Masc", "Masc,Neut", "Neut"],
        "InflClass": ["Ind", "IndEurA", "IndEurI", "IndEurO", "LatPron"],
        "NumForm": ["Digit", "Reference", "Roman", "Word"],
        "NumType": ["Card", "Frac", "Ord"],
        "Number": ["Plur", "Sing"],
        "PronType": ["Rcp"],
        "Proper": ["Yes"],
        "Typo": ["Yes"]
    },
    "PART": {
        "Abbr": ["Yes"],
        "AdpType": ["Prep"],
        "Case": ["Nom", "Voc"],
        "Clitic": ["Yes"],
        "Compound": ["Yes"],
        "Dialect": ["Munster", "Ulster"],
        "Form": ["Direct", "Ecl,Indirect", "Emp", "Indirect", "Len", "VF"],
        "Gender": ["Neut"],
        "Mood": ["Imp", "Sub"],
        "Number": ["Sing"],
        "PartType": ["Ad", "Aug", "Cmpl", "Comp", "Cop", "Dct", "Deg", "Emp", "Inf", "Int", "Num", "Pat", "Sup", "Vb", "Voc"],
        "Person": ["3"],
        "Polarity": ["Neg"],
        "Prefix": ["Yes"],
        "PronClass": ["A"],
        "PronNum": ["Plur"],
        "PronPers": ["1"],
        "PronType": ["Dem", "Dem,Rel", "Int", "Prs", "Rel"],
        "Tense": ["Past"],
        "Typo": ["Yes"],
        "VerbForm": ["Cop"]
    },
    "PRON": {
        "Abbr": ["Yes"],
        "Case": ["Abl", "Acc", "Dat", "Gen", "Nom", "Voc"],
        "Compound": ["Yes"],
        "Definite": ["Def", "Ind"],
        "Degree": ["Sup"],
        "Dialect": ["Connaught", "Munster", "Ulster"],
        "Foreign": ["Yes"],
        "Form": ["Emp", "HPref", "Len", "VF"],
        "Gender": ["Fem", "Fem,Masc", "Fem,Neut", "Masc", "Masc,Neut", "Neut"],
        "InflClass": ["Ind", "IndEurO", "IndEurX", "LatAnom", "LatPron"],
        "NumType": ["Ord"],
        "Number": ["Plur", "Sing"],
        "Person": ["1", "2", "3"],
        "Polarity": ["Neg"],
        "Poss": ["Yes"],
        "PronClass": ["A", "B", "C"],
        "PronType": ["Ana", "Dem", "Dem,Prs", "Emp", "Ind", "Ind,Int", "Ind,Neg", "Ind,Rel", "Int", "Int,Rel", "Neg", "Prs", "Rcp", "Rel", "Tot", "Void"],
        "Proper": ["Yes"],
        "Reflex": ["Yes"],
        "Style": ["Arch", "Coll", "Expr", "Slng", "Vrnc"],
        "Typo": ["Yes"],
        "VerbForm": ["Cop"]
    },
    "PROPN": {
        "Abbr": ["Yes"],
        "Case": ["Abl", "Acc", "Dat", "Gen", "Loc", "Nom", "Voc"],
        "Compound": ["Yes"],
        "Definite": ["Def"],
        "Degree": ["Pos"],
        "Dialect": ["Munster"],
        "Foreign": ["Yes"],
        "Form": ["Ecl", "HPref", "Len"],
        "Gender": ["Fem", "Fem,Masc", "Masc", "Masc,Neut", "Neut"],
        "InflClass": ["Ind", "IndEurA", "IndEurI", "IndEurO", "IndEurU", "IndEurX"],
        "NameType": ["Ast", "Cal", "Geo", "Giv", "Lit", "Oth", "Rel", "Sur"],
        "NounType": ["Strong", "Weak"],
        "NumForm": ["Word"],
        "NumType": ["Card"],
        "Number": ["Plur", "Sing"],
        "Polarity": ["Neg"],
        "Proper": ["Yes"],
        "Reflex": ["Yes"],
        "Style": ["Expr"],
        "Typo": ["Yes"],
        "Variant": ["Greek"]
    },
    "PUNCT": {
        "Degree": ["Pos"],
        "Number": ["Sing"],
        "Typo": ["Yes"]
    },
    "SCONJ": {
        "Abbr": ["Yes"],
        "AdvType": ["Loc"],
        "Case": ["Nom"],
        "Compound": ["Yes"],
        "ConjType": ["Cmpr"],
        "Degree": ["Pos"],
        "Form": ["Emp", "Len", "VF"],
        "NumType": ["Card"],
        "Polarity": ["Neg"],
        "PronGend": ["Neut"],
        "PronNum": ["Sing"],
        "PronPers": ["3"],
        "PronType": ["Con", "Dem", "Int", "Prs", "Rel"],
        "Style": ["Vrnc"],
        "Tense": ["Past", "Pres"],
        "Typo": ["Yes"],
        "VerbForm": ["Cop", "Fin", "Ger", "Part"]
    },
    "SYM": {
        "Abbr": ["Yes"],
        "Foreign": ["Yes"],
        "Number": ["Sing"]
    },
    "VERB": {
        "Abbr": ["Yes"],
        "Aspect": ["Hab", "Imp", "Inch", "Perf", "Prosp"],
        "Case": ["Abl", "Acc", "Dat", "Gen", "Loc", "Nom", "Voc"],
        "Compound": ["Yes"],
        "Degree": ["Abs", "Cmp", "Pos"],
        "Dialect": ["Munster"],
        "ExtPos": ["ADP"],
        "Form": ["Direct", "Direct,Emp", "Ecl", "Ecl,Emp", "Emp", "Emp,Len", "HPref", "Len"],
        "Gender": ["Fem", "Fem,Masc", "Masc", "Masc,Neut", "Neut"],
        "InflClass": ["LatA", "LatAnom", "LatE", "LatI", "LatI2", "LatX"],
        "InflClass[nominal]": ["Ind", "IndEurA", "IndEurI", "IndEurO", "IndEurU", "IndEurX"],
        "Mood": ["Cnd", "Cnd,Int", "Imp", "Ind", "Sub"],
        "Number": ["Plur", "Sing"],
        "PartType": ["Aug"],
        "Person": ["0", "1", "2", "3"],
        "Polarity": ["Neg"],
        "PronType": ["Rel"],
        "Proper": ["Yes"],
        "Tense": ["Fut", "Past", "Pqp", "Pres"],
        "Typo": ["Yes"],
        "VerbForm": ["Fin", "Gdv", "Ger", "Inf", "Part", "Sup"],
        "VerbType": ["Mod"],
        "Voice": ["Act", "Pass"]
    },
    "X": {
        "Abbr": ["Yes"],
        "Case": ["Nom"],
        "Compound": ["Yes"],
        "Foreign": ["Yes"],
        "Form": ["Ecl", "HPref"],
        "NameType": ["Geo", "Rel", "Sur"],
        "Number": ["Sing"],
        "Polarity": ["Neg"],
        "Proper": ["Yes"],
        "Typo": ["Yes"]
    },
    "_": {}
};